# -*- coding: utf-8 -*-
"""Amazon Web Scraper Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12CpDsTAFpA1ggRFe0MU5chTL3N_0DFcZ
"""

from bs4 import BeautifulSoup
import requests
import time
import datetime
import smtplib

url='https://www.amazon.com/funny-analyst-definition-scientist-t-shirt/dp/B07NLP2PKY'
headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

page=requests.get(url, headers=headers)
soup1=BeautifulSoup(page.content, 'lxml')
soup2=BeautifulSoup(soup1.prettify(), 'lxml')
try:
  title=soup2.find(id='productTitle').get_text()
except AttributeError:
     print ("No Title")
try:
    price=soup2.find(class_='a-form-label').get_text.strip()[1:]
except AttributeError:
    print('No price')

import datetime
today=datetime.date.today()
print(today)

import csv
header=['Title', 'Price', 'Date']
data=[today]
with open('AmazonWebScraperDataset.csv', 'w', newline='', encoding='UTF8') as f:
  writer=csv.writer(f)
  writer.writerow(header)
  writer.writerow(data)

import pandas as pd
df=pd.read_csv(r'/content/AmazonWebScraperDataset.csv')
print(df)

with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
  writer=csv.writer(f)
  writer.writerow(data)

def check_price():
  url='https://www.amazon.com/funny-analyst-definition-scientist-t-shirt/dp/B07NLP2PKY'
  headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}
  page=requests.get(url, headers=headers)
  soup1=BeautifulSoup(page.content, "lxml")
  soup2=BeautifulSoup(soup1.prettify(), 'lxml')
  try:
    title=soup2.find(id='productTitle').get_text()
  except AttributeError:
    print ("No Title")
  try:
    price=soup2.find(class_='a-form-label').get_text.strip()[1:]
  except AttributeError:
    print('No price')

  import datetime
  today=datetime.date.today()
  print(today)

  import csv
  header=['Date']
  data=[today]

  with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
    writer=csv.writer(f)
    writer.writerow(data)

while (True):
  check_price()
  time.sleep(86400)

import pandas as pd
df=pd.read_csv(r'/content/AmazonWebScraperDataset.csv')
print(df)

